### ISSUE TITLE
Visualizations: documentation on variable constraints in the “Learn more” link is out of date

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#575] opened 2021-09-29 23:28 UTC
using the WASH-b Kenya study, I made a box plot of LAZ (participant repeated measure entity) for each study arm (community entity). I'd like to overlay this by either "study timepoint" or "diarrhea in last 7 days" (both under participant repeated measure entity) but I can only select overlay variables in the community entity

![image](https://user-images.githubusercontent.com/25450900/135361826-6c093b9c-7a4f-4820-9663-6cf6f566999e.png)

**Comment by danicahelb** [comment] 2022-02-08 22:58
Variable constraint documentation has been added, but it is out of date now that we are no longer inferring data shape. The text needs to be updated:

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/25450900/153089784-368278be-dad1-4938-8028-e88da4e1b31d.png">

**Comment by SheenaTomko** [comment] 2022-02-23 20:02
Moving this to failed qa for now because I made some changes to the text at https://github.com/VEuPathDB/web-eda/blob/variable-constraints/src/lib/core/components/docs/variable-constraints.tsx. 
Danielle will review and submit the pull request.

**Comment by SheenaTomko** [comment] 2022-02-24 14:54
@d-callan Now when I try to click on the "Learn more" link, I don't get the expected pop-up with the documentation on variable constraints.

**Comment by d-callan** [comment] 2022-02-24 15:01
its just worked for me on qa.restricted, and appears to have your updates there.. where did you try and what did you get?

**Comment by danicahelb** [comment] 2022-02-24 19:42
it works for me too. @SheenaTomko please provide more info on how to recreate. thanks!

**Comment by SheenaTomko** [comment] 2022-02-24 19:50
Closing this. Reviewed the page that Danielle provided a link for and the text looks good. Created a separate ticket for the issue with the pop-up not appearing (so far no one else has been able to reproduce)

https://github.com/VEuPathDB/EdaNewIssues/issues/162

**Closed by SheenaTomko** 2022-02-24 19:50 UTC
Labels: enhancement, medium cost, b56
