### ISSUE TITLE
For very large / small numbers, use formatting standard to epidemiologists

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1275] opened 2022-07-18 18:43 UTC
When extreme range selections are made, the default notation for axes labels used by plotly is not standard in the field of epidemiology

- Plotly defaults: 100n, 1u, 10u etc…
- Ideal formatting: 1.5 x 10<sup>-5</sup>, 4.6 x 10<sup>10</sup>, etc
- Also acceptable: 1.5e-5, 4.6e10, etc

To reproduce (after log scale and related axis work has been completed for https://github.com/VEuPathDB/web-eda/issues/1228 and https://github.com/VEuPathDB/web-eda/issues/1157):

GEMS1

- Scatter plot
- Put "Household wealth, numerical on either axis (and choose another variable for the other axis)
- Choose logs for the household wealth axis
- Modify its lower range to 0.00000005 or thereabouts.

**Comment by moontrip** [comment] 2022-07-28 18:52
I have looked at plotly.js API docs and tested something. From my understanding, this is doable but will wait for the implementation as indicated in the ticket. For a record, here is a solution:

layout.yaxis.showexponent: 'all',
layout.yaxis.minexponent: 4,
layout.yaxis.exponentformat: 'power',

note) exponentformat of 'power' displays the above ideal format like 1.5 x 10^-5, 4.6 x 10^10, etc
minexponent determines when we will show exponent. Its input is absolute value, meaning that if 4 (power), then values with power of (+/-5) or larger (> 10^5) / smaller (< 10^-5) will start to show the exponent.

**Comment by danicahelb** [comment] 2022-08-17 22:25
Hi @moontrip it seems like this can happen on any axis where the user can both (i) select log scale and (ii) set either a very small value for minimum or very large value for the maximum of the axis range

this is not a priority for b59 so i am moving the ticket to "Backlog"

![Image](https://user-images.githubusercontent.com/25450900/185254273-b1569214-0f5f-458b-b620-73f20333be85.png)

**Comment by danicahelb** [comment] 2022-08-31 19:32
@moontrip this is very low priority, i will let you know when you should work on it. i've moved it back to Backlog

**Comment by moontrip** [comment] 2022-08-31 20:19
@danicahelb Thank you for your information. I think that it is close to the end as there already exists PR with a couple of reviews.

**Comment by moontrip** [comment] 2022-09-06 16:35
closing due to merges: https://github.com/VEuPathDB/web-components/pull/384 & https://github.com/VEuPathDB/web-eda/pull/1348

**Closed by moontrip** 2022-09-06 16:35 UTC

**Comment by sweverschulman** [comment] 2022-10-21 14:56
Functionality works. Confirmed using both GEMS 1 example (scatter plot) and a line plot in MAL-ED
<img width="553" alt="Screen Shot 2022-10-21 at 10 44 48 AM" src="https://user-images.githubusercontent.com/62298921/197226027-12d0fd3f-9a9a-4408-b308
<img width="547" alt="Screen Shot 2022-10-21 at 10 44 56 AM" src="https://user-images.githubusercontent.com/62298921/197226037-73f424f7-4575-4874-bae4-c52d583372a4.png">
-20c46c80ab2f.png">
