### ISSUE TITLE
Study details stand alone page and/or tab for "Prerelease" and "Private" studies

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/web-eda#809] opened 2022-01-18 20:53 UTC
Jay loaded the study characteristics and everything from the ClinEpiPresenter that's needed for the all studies table and study details page for the "Prerelease" studies: India ICEMR DAMaN Quasi-experimental Stepped-wedge, LAKANA Cluster Randomized Trial, Namibia rfMDA RAVC Cluster Randomized Trial, and PERCH Case Control. 

We would like a user to be able to click on the name of this study and be re-directed to the study details tab for it. However, at the moment, the user first gets a pop-up like the one below, and if they click the link, they get a page with an error message. 

<img width="753" alt="Screen Shot 2022-01-18 at 2 41 38 PM" src="https://user-images.githubusercontent.com/54597319/150015353-746344cc-5824-4b9b-a44b-aa27b65f0907.png">

_Error message:_
<img width="1009" alt="Screen Shot 2022-01-18 at 2 41 45 PM" src="https://user-images.githubusercontent.com/54597319/150015360-83faf649-219c-4604-a922-0320b9ff9247.png">

As a reminder, "Prerelease" studies are studies with data that we plan to load (and in some cases have already loaded), where we want the study card and study page to be publicly accessible before the data is released. 

Proposal:
1. Have all links for a "Prerelease" study re-direct to the "View study details" tab
2. Grey out all other tabs (Browse and Subset, Visualize, etc.) and make them unclickable or remove them completely
3. Remove the entity diagram
4. Remove the "New Analysis",  "My analyses", and "Make Analysis Public" links
5. If someone is logged into a ClinEpi account that has access to the study, and there is real data loaded, they should be able to see the EDA appear as normal for that study (this can be done for a later release if needed)

**Comment by danicahelb** [comment] 2022-01-31 22:46
Discussed in 1/28/2022 EDA meeting:

Stand-alone study pages are needed for both prerelease and private studies. Currently, users cannot access the study page (the link in the popup currently takes you to “Page not found”; we need this link to take the user to a stand-alone study page)

- We need a new attribute in the presenter so that the client code can discover that there is no data. This attribute will only be filled out for studies with no data (or for studies where Jay has loaded dummy data)

**For private studies:** 
- Data is always loaded
- The stand-alone study page should have a banner indicating that this is a PRIVATE study and a link for providers/users to login or submit a request
- Users must have an approved access request to see even aggregate data
- We will manually give study providers access to their private studies. When logged in, providers should be able to access all EDA tabs (view study page, browse & subset, visualize, notes, and download)
- Note: studies that are pre-release on the live site are private on the QA site so that providers for various studies cannot access data from other studies before it is released

**For prerelease studies where data is available on the live site:**
- The stand-alone study page should have a banner indicating that this is a PRERELEASE study and indicate that users can contact the original study team directly for the data before it is made available on ClinEpiDB (see PERCH)
- We will manually give study providers access to their private studies. When logged in, providers should be able to access all EDA tabs (view study page, browse & subset, visualize, notes, and download). _Note: the banner will not contain a link for providers to login. Is this ok???_
- Users cannot request access to study data through ClinEpiDB
- Note: “Prerelease” access level is NOT relevant to the QA site. Pre-release studies that have data loaded on the live site will be marked as “Private” on the QA site

**For prerelease studies where data is NOT yet available on the live site:**
- Pre-release studies with no data should just have access to the stand-alone study page
- The stand-alone study page should have a banner indicating that this is a PRERELEASE study and indicate that users can contact the original study team directly for the data before it is made available on ClinEpiDB (see PERCH)
-Users cannot request access to study data through ClinEpiDB
-Providers will only be able to see the stand-alone study page and will not be able to access all EDA tabs (because data has not yet been loaded)

**Comment by dmfalke** [comment] 2022-02-15 22:11
Note: I did not add the banner to the page for private studies. We hadn't done this in the past, so I thought I would ask. It shouldn't be too hard to add.

**Comment by nkittur-uga** [comment] 2022-02-16 14:34
So...this one is almost there. When I try to access a private/prerelease study, I get this error pop-up, however when I chose the error pop-up, the study page is there and looks great. 
<img width="1278" alt="Screen Shot 2022-02-16 at 9 32 40 AM" src="https://user-images.githubusercontent.com/67710160/154286484-50f92384-76dd-4802-b251-44234c16c2f5.png">

**Comment by dmfalke** [comment] 2022-02-16 14:36
Ah, strange. That wasn’t happening on my development site. I’ll take a look!

**Comment by dmfalke** [comment] 2022-02-16 14:52
I am not able to reproduce. In what browser is this happening?

**Comment by nkittur-uga** [comment] 2022-02-16 14:54
Chrome.

**Comment by nkittur-uga** [comment] 2022-02-16 14:59
All studies denoted "Private" need a button on the study page to request access to the data. 

Clicking on this button will prompt users to log in, and if their accounts have been added as study team members, then they can access the data for QA. This feature isn’t essential for b56, but should be prioritized right after all essential functionality for b56 is done, because study teams will be looking at their private studies for QA.

**Comment by nkittur-uga** [comment] 2022-02-16 15:04
Yes, unfortunately still happening for all private and prerelease studies.

**Comment by dmfalke** [comment] 2022-02-16 15:10
I'm going to need some more details about this error. Maybe we can chat on slack later.

**Comment by dmfalke** [comment] 2022-02-16 15:11
> All studies denoted "Private" need a button on the study page to request access to the data.
> 
> Clicking on this button will prompt users to log in, and if their accounts have been added as study team members, then they can access the data for QA. This feature isn’t essential for b56, but should be prioritized right after all essential functionality for b56 is done, because study teams will be looking at their private studies for QA.

Ah, yes, this makes sense. Since we are redirecting to the standalone page, the typical popup is not seen. I will work on this.

**Closed** 2022-02-23 03:58 UTC
Labels: medium cost, high priority, b56

**Comment by nkittur-uga** [comment] 2022-02-24 16:07
<img width="1333" alt="Screen Shot 2022-02-24 at 11 03 35 AM" src="https://user-images.githubusercontent.com/67710160/155561956-8d0fb8b7-8826-4f87-9241-c6474d3eb39b.png">
Banner is seen as expected.
