### ISSUE TITLE
Viz tab log scale cuts points in half

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1231] opened 2022-06-21 21:25 UTC
I made this scatterplot with PRISM data
<img width="718" alt="image" src="https://user-images.githubusercontent.com/25450900/174899964-96482e0d-3ab2-458b-a7e3-9fecba926428.png">

Notice that the x-axis point at 1011 is cut in half. please adjust the plot area so that the whole point is displayed. thanks!

**Comment by moontrip** [comment] 2022-08-08 17:07
Somehow I could not make the plot as I keep getting 500 errors - tested with my dev. qa and qa restricted do not lead to viz with a message "Data for this study is not currently available."

**Comment by dmfalke** [comment] 2022-08-09 14:02
I was able to recreate on the production site. Note that the x-axis has log scale turned on (probably obvious from tick marks). Perhaps this is resolved by #1241. I suspect data is being reloaded on the qa sites.

**Comment by moontrip** [comment] 2022-08-24 20:37
I have checked this as the data finally showed up for me. In summary I cannot reproduce the behavior, probably owing to https://github.com/VEuPathDB/web-eda/pull/1241 thus I will close this ticket.

Here is a screenshot for the same example above and now it has a padding in the max range:
![1231_1](https://user-images.githubusercontent.com/12802305/186518561-43bf9f5f-366a-4252-80ca-1fd7b3d076be.png)

**Closed by moontrip** 2022-08-24 20:37 UTC
Labels: bug

**Comment by aaronwlsong** [comment] 2022-08-26 14:32
Looks good now, the maximum value is fully in the plot. Closing ticket.



![Image](https://user-images.githubusercontent.com/61077845/186927888-e8cf3da2-12f4-4ff1-9335-167447788c9a.png)
