### ISSUE TITLE
Map tool need loading indicator

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1118] opened 2022-05-03 17:41 UTC
after I select the main var on the map tool, i see the map marker come up on the screen, but the screen seems to be frozen (I cannot scroll down to the plot modes section). I think this is because the map is still loading. a while later, the map zooms out a bit so that i can see more of the geographic context for the original marker. after this happens, i am then able to scroll.

We need a loading indicator so that the user knows to keep waiting before trying to poke around on the site

**Comment by bobular** [comment] 2022-05-16 10:47
Even with UMSP and main var "malaria diagnosis" I see a pink spinner in the center of the map, and I am able to scroll the page up and down to see the plot option radio buttons.

So I cannot reproduce on my slow-ish laptop with Windows 10 + latest FF.

**Comment by dmfalke** [comment] 2022-05-17 18:16
What Danica is describing sounds like the main rendering thread is locked up. This could happen if a lot of things are being render on screen at the same time, such as many markers, or markers with lots of data points. It could also be due to unrelated system activity. A specific study where this is know to happen would be helpful.

**Comment by bobular** [comment] 2022-06-08 15:50
Possibly related to freezing in chrome issue (web-components? TBC)

**Comment by bobular** [comment] 2022-06-15 13:07
Pretty sure this is resolved by #1201

**Closed by bobular** 2022-06-15 13:07 UTC
Labels: question, high priority

**Comment by bobular** [comment] 2022-06-15 13:09
@danicahelb please try to reproduce when https://github.com/VEuPathDB/web-components/issues/360 has been deployed and is in "ready to be tested"

**Comment by bobular** [comment] 2022-06-15 18:03
Note that we have discovered today that the "Chrome map freezing" issue has not completely gone away... So this issue may still occur.

**Comment by SAK22** [comment] 2022-06-16 16:11
Pink spinner still there but can scroll

**Comment by SAK22** [comment] 2022-06-21 16:51
Working well today
