### ISSUE TITLE
General: allow users to make "Public analyses"

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#621] opened 2021-09-18 04:08 UTC
Related to this phase 1 ticket: https://github.com/VEuPathDB/web-eda/issues/392

Discussed in 9/18 ClinEpi UX meeting:

Front end needs UI development to support users making their strategies public. We won’t have this in place for Phase 1.
- We need to guide users towards how to make their strategy public 
- We need to provide a way for users to fill out the study description

Perhaps users could fill out the study description (needed for making an analysis public) within a notes tab (see https://github.com/VEuPathDB/EdaClinepiPhase2NewIssues/issues/15)
UI for making public analyses could guide them to filling out a designated section within the notes tab

**Comment by steve-fischer-200** [comment] 2021-10-21 16:13
this issue is basically a duplicate of https://github.com/VEuPathDB/web-eda/issues/620

**Closed by steve-fischer-200** 2021-10-21 16:13 UTC
