### ISSUE TITLE
Visualizations: Birds-eye bar location and styling

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/web-eda#419] opened 2021-09-10 15:30 UTC
Given its meant to provide a high-level sense for whats being plotted in the primary plot, i imagine it above the plot rather than below it. I also think it should be wider. Perhaps match the width of the primary plot?

**Comment by bobular** [comment] 2021-09-15 17:48
It's supposed to be to the right hand side.

Do you have a very narrow screen?

**Comment by d-callan** [comment] 2021-09-20 15:18
i do have a narrow laptop screen. when im using that things often look kind of bad tbh, like a randomly ordered list of things w random widths. the mosaic plots in particular, since the widths of the two tables are different.

**Comment by danicahelb** [comment] 2021-09-21 00:54
Discussed in 9/20 EDA mtg

- This is a window resolution issue: 1280 pixels → switches from side by side view to top/bottom view
- Revisit default resolution behavior so that the switch to top/bottom view only occurs on mobile / very small windows
- Can we determine average screen resolution for ClinEpi users from awstats? 
-

**Comment by bobular** [comment] 2021-09-22 10:08
Clarification: ideally we want to tweak the layout so that the birds eye bar doesn't go underneath on screens 1280 px and bigger.

If users have windows smaller than that, this is their problem!

Google Analytics definitely has screen/browser sizes.

**Comment by bobular** [comment] 2021-09-22 12:12
Trivially reducing the width of the birds-eye and coverage table from 500 to 400px makes things fit in a 1280px screen.
However, the height of the birds eye mouseover legend is greatly increased as a result. See below

![image](https://user-images.githubusercontent.com/308639/134340959-4c05c4b9-5026-4466-93cd-5d904e099ed5.png)

**Comment by bobular** [comment] 2021-09-22 12:17
Might as well put them horizontal? They take the same amount of vertical space!

![image](https://user-images.githubusercontent.com/308639/134341941-d3370c42-2b68-40a9-886c-c37c0770e6b1.png)

**Comment by bobular** [comment] 2021-09-29 14:13
Maybe while doing this ticket we should think about using more horizontal screen space in the viz tab when available.  The sizings that work for 1280px will look a bit odd on bigger screens.

**Comment by danicahelb** [comment] 2021-10-02 04:53
We discussed in the 10/1 UX meeting. Neither option for mouseovers proposed above is satisfactory.

Instead, we would like to have tool tips for the brackets and use a legend style for subset & all data 
@danicahelb will make mockups

**Comment by danicahelb** [comment] 2021-10-05 03:55
We discussed further in 10/4 EDA meeting, and @asizemore discussed a new idea with @danicahelb after the meeting, via Slack.

Final decision on mouseover styling is pending input from the broader group. Ticket is paused until then.

**Comment by danicahelb** [comment] 2021-10-14 15:30
The issue is still happening for me. you are right, it only happens when I've subsetted the data. good detective work @bobular 

![image](https://user-images.githubusercontent.com/25450900/137349522-5598f3cd-e3b4-485e-9a2c-8ceea9fc998b.png)

**Comment by danicahelb** [comment] 2021-10-14 17:50
@bobular hopefully your change fixes it. regardless, I am moving this ticket into phase 2 for further testing as it can be rolled out in b55 if it is still not fixed. thanks

**Closed** 2021-10-14 18:32 UTC
Labels: low cost, styling

**Comment by danicahelb** [comment] 2021-11-03 20:11
looks great now, thanks!

![image](https://user-images.githubusercontent.com/25450900/140185375-8477284e-06c2-40de-b59b-c6df9daf7a8f.png)
