### ISSUE TITLE
Subsetting: in categorical filter, when user selects "all," do not add a filter

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/web-eda#28] opened 2021-03-31 21:52 UTC
1. When selecting all countries in Households/Country
https://localhost:3000/eda/DS_841a9f5259/2/variables/PCO_0000024/ENVO_00000004
the filter sent to the back end includes all the country options, and a 'chip' is added unnecessarily.

2. If I click on Bangladesh, it creates the correct filter.  If I click on the column heading checkbox to select-all, it creates a filter with Bangladesh twice.
{"entityId":"PCO_0000024","variableId":"ENVO_00000004","stringSet":["Bangladesh","India","Kenya","Mali","Mozambique","Pakistan","The Gambia","Bangladesh"],"type":"stringSet"}

**Comment by dmfalke** [comment] 2021-04-03 03:41
This should be addressed in https://github.com/VEuPathDB/web-eda/blob/main/src/lib/core/components/filter/TableFilter.tsx#L254-L280.

For (1), add a condition to the first if-statement to check that `values` is the same as `allValues`.

(2) may be a bug in https://github.com/VEuPathDB/WDKClient/blob/master/Client/src/Components/AttributeFilter/MembershipField.jsx#L311

**Comment by bobular** [comment] 2021-07-24 15:02
I'm not so sure about addressing 1) with something like

```
      if (values.length === 0 || isEqual(values, allValues)) {
        analysisState.setFilters(otherFilters);
      } else {
```
because it doesn't allow an "all-items-selected" filter state to be stored in analysisState, and therefore no `filter` is passed as a prop to `MembershipField`.

So clicking on the "check all" or clicking all the items (in any order) makes the selections and filter go away, disconcertingly.

**Comment by bobular** [comment] 2021-07-24 15:33
But 2) was easy enough to fix in https://github.com/VEuPathDB/WDKClient/pull/138

We will have to close this ticket manually, as there are no changes in EDA itself (assuming it's OK to ignore sub-issue 1.)

**Comment by danicahelb** [comment] 2021-08-18 04:25
I think (1) is a feature not a bug. 

Using your country example, if <100% of Households had country data, I can check all countries to filter out the Households that were missing country data.

I think we can live with the unneccessary chip in instances where 100% of the Households have data for the variable where all values are selected.

**Comment by danicahelb** [comment] 2021-08-18 04:26
@aaronwlsong assigning to you to QA. Let me know if you have questions

**Comment by aaronwlsong** [comment] 2021-08-19 14:39
QA checking:

2.If I click on Bangladesh, it creates the correct filter. If I click on the column heading checkbox to select-all, it creates a filter with Bangladesh twice.
{"entityId":"PCO_0000024","variableId":"ENVO_00000004","stringSet":["Bangladesh","India","Kenya","Mali","Mozambique","Pakistan","The Gambia","Bangladesh"],"type":"stringSet"}

Did not find this issue on QA website.
a. Choose country="Bangladesh"
<img width="2034" alt="WeChata21cc7753e2ecc8bfacdca61f3183670" src="https://user-images.githubusercontent.com/61077845/130088123-a296abfc-bb92-49d8-b5f7-a30d3c0ae661.png">

b.Choose heading checkbox to select-all:
<img width="2042" alt="WeChat69cc60375c89b6525ed2fb96d92a03b4" src="https://user-images.githubusercontent.com/61077845/130088359-8fba7608-7bd2-4a34-aa10-b307b0901d0a.png">

**Closed** 2021-08-19 18:34 UTC
Labels: bug
