### ISSUE TITLE
General: Oops message covers entire page if one of the viz tab thumbnails err

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/web-eda#365] opened 2021-08-25 01:55 UTC
not only are we covering things that are working, its very disorienting to lose all the navigation and ability to start a new analysis..

to reproduce, for score mansoni try to make a box plot of study timepoint against birth year. then after it errs start again w the same study and try to navigate to the viz tab.

**Comment by danicahelb** [comment] 2021-12-02 16:41
I cannot reproduce, perhaps this has been fixed already? @d-callan can you take a look and let me know if we can close this ticket? 

![image](https://user-images.githubusercontent.com/25450900/144464802-3efcf4dd-0c07-4315-b562-3fe6a490eaec.png)

**Comment by chowington** [comment] 2021-12-15 20:18
I was also unable to reproduce the specific case mentioned, and I tried to introduce bugs to cause an Oops due to the thumbnail on the visualizations summary tab, but couldn't. It looks like bugs that happen in the thumbnail creation logic would occur in the expanded visualization screen, not the visualizations summary screen. Does this sound correct @jtlong3rd?

Also @jtlong3rd or @dmfalke, is there anywhere else that would benefit from an error boundary?

**Comment by jtlong3rd** [comment] 2021-12-15 21:01
> I was also unable to reproduce the specific case mentioned, and I tried to introduce bugs to cause an Oops due to the thumbnail on the visualizations summary tab, but couldn't. It looks like bugs that happen in the thumbnail creation logic would occur in the expanded visualization screen, not the visualizations summary screen. Does this sound correct @jtlong3rd?

Exactly right - thumbnail creation is triggered by the `useUpdateThumbnailEffect` hook, which is only invoked in the various "expanded visualization" components.

**Comment by dmfalke** [comment] 2021-12-16 05:05
> Also @jtlong3rd or @dmfalke, is there anywhere else that would benefit from an error boundary?

I think it would be a good idea to add one to each `Route` component in https://github.com/VEuPathDB/web-eda/blob/main/src/lib/workspace/AnalysisPanel.tsx. This would allow users to switch to other analysis tabs. There may be other places that make sense, both above and below in the component hierarchy.

**Closed** 2021-12-22 18:17 UTC
Labels: bug, low cost

**Comment by sweverschulman** [comment] 2022-02-04 19:19
I too was unable to reproduce this error. Is it our assumption that the bug is now fixed? @danicahelb @danicahelb ?

**Comment by SheenaTomko** [comment] 2022-02-04 19:28
Yes, if you can no longer reproduce the error and see no other issues, then the bug is fixed and you can move the ticket to complete
